#ifndef DEFS_H
#define DEFS_H

// RENDERING TYPE

#define RENDERING_TYPE_PLAYER 0
#define RENDERING_TYPE_NPC 1

// RENDERING DELAY

#define HEAD_TEXTURE_DELAY 1
#define BODY_TEXTURE_DELAY 3
#define LEGS_TEXTURE_DELAY 1

// ALL TEXTURE TYPES

#define ALL_TEXTURE_TYPE 6

// TEXTURE TYPE'S ID

#define TEXTURE_TYPE_NPC 0
#define TEXTURE_TYPE_ARMOR_HEAD 1
#define TEXTURE_TYPE_ARMOR_BODY 2
#define TEXTURE_TYPE_ARMOR_LEGS 3
#define TEXTURE_TYPE_FREED 4
#define TEXTURE_TYPE_TILE 5

// MAX TEXTURE'S TYPE

#define MAX_TILE_TEXTURE 623
#define MAX_NPC_TEXTURE 432
#define MAX_ARMOR_HEAD_TEXTURE 1
#define MAX_ARMOR_BODY_TEXTURE 1
#define MAX_ARMOR_LEGS_TEXTURE 1
#define MAX_FREED_TEXTURE 12

// TILE TEXTURE

#define DIRT_TILE_TEXTURE 0
#define STONE_TILE_TEXTURE 1

// FREED TEXTURE

#define BACKGROUND_TEXTURE 0

#define BODY_TEXTURE 1
#define HEAD_TEXTURE 2
#define LEGS_TEXTURE 3
#define EYE1_TEXTURE 4
#define EYE2_TEXTURE 5
#define HAIR_TEXTURE 6
#define ARMS_TEXTURE 7
#define SHOES_TEXTURE 8

#define ARMOR_BODY_TEXTURE 9
#define ARMOR_HEAD_TEXTURE 10
#define ARMOR_LEGS_TEXTURE 11

// TEXTURE ACTIONS

#define TEXTURE_IDLE 0
#define TEXTURE_MOVING 1
#define TEXTURE_JUMPING 2
#define TEXTURE_ATTACK 3


// NPC TEXTURES

#define SLIME_TEXTURE 1
#define EYE_TEXTURE 2
#define ZOMBIE_TEXTURE 3
#define MUMMY_TEXTURE 78
#define DARK_MUMMY_TEXTURE 79
#define BLOOD_MUMMY_TEXTURE 80
#define FROZEN_ZOMBIE_ARM 431

#endif